server:
  port: 8449
#  tomcat:
#    ajp:
#      enabled: true
#      port: 8021

spring:
  main:
    allow-circular-references: true
  # JSP 경로 설정
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.200.173.253:3306/meetingRoom
    username: meet
    password: ghldmltlf2023!@
    
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true